<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class M_komputer extends CI_Model
{

    public $table = 'tb_komputer';
    public $id = 'id_komputer';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_komputer', $q);
	$this->db->or_like('ip_adres', $q);
	$this->db->or_like('ip_gateway', $q);
	$this->db->or_like('nama_kom', $q);
	$this->db->or_like('nama_user', $q);
	$this->db->or_like('jenis_inter', $q);
	$this->db->or_like('level_inter', $q);
	$this->db->or_like('jenis_deks_netbook', $q);
	$this->db->or_like('merek_deks_netbook', $q);
	$this->db->or_like('tipe_deks_netbook', $q);
	$this->db->or_like('os', $q);
	$this->db->or_like('merek_monit', $q);
	$this->db->or_like('size_monit', $q);
	$this->db->or_like('merek_procesr', $q);
	$this->db->or_like('tipe_procesr', $q);
	$this->db->or_like('speed_procesr', $q);
	$this->db->or_like('amount_ram', $q);
	$this->db->or_like('tipe_ram', $q);
	$this->db->or_like('merek_hards', $q);
	$this->db->or_like('size_hards', $q);
	$this->db->or_like('merek_grapc', $q);
	$this->db->or_like('tipe_grapc', $q);
	$this->db->or_like('memory_grapc', $q);
	$this->db->or_like('mobo', $q);
	$this->db->or_like('power_suply', $q);
	$this->db->or_like('mouse', $q);
	$this->db->or_like('keyboard', $q);
	$this->db->or_like('apk_terinstall', $q);
	$this->db->or_like('ups', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_komputer', $q);
	$this->db->or_like('ip_adres', $q);
	$this->db->or_like('ip_gateway', $q);
	$this->db->or_like('nama_kom', $q);
	$this->db->or_like('nama_user', $q);
	$this->db->or_like('jenis_inter', $q);
	$this->db->or_like('level_inter', $q);
	$this->db->or_like('jenis_deks_netbook', $q);
	$this->db->or_like('merek_deks_netbook', $q);
	$this->db->or_like('tipe_deks_netbook', $q);
	$this->db->or_like('os', $q);
	$this->db->or_like('merek_monit', $q);
	$this->db->or_like('size_monit', $q);
	$this->db->or_like('merek_procesr', $q);
	$this->db->or_like('tipe_procesr', $q);
	$this->db->or_like('speed_procesr', $q);
	$this->db->or_like('amount_ram', $q);
	$this->db->or_like('tipe_ram', $q);
	$this->db->or_like('merek_hards', $q);
	$this->db->or_like('size_hards', $q);
	$this->db->or_like('merek_grapc', $q);
	$this->db->or_like('tipe_grapc', $q);
	$this->db->or_like('memory_grapc', $q);
	$this->db->or_like('mobo', $q);
	$this->db->or_like('power_suply', $q);
	$this->db->or_like('mouse', $q);
	$this->db->or_like('keyboard', $q);
	$this->db->or_like('apk_terinstall', $q);
	$this->db->or_like('ups', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

     public function carii($pilih,$detail)
        {
            $this->db->from('tb_komputer');
            $this->db->like($pilih,$detail);
            return $this->db->get();
            }
}

/* End of file M_komputer.php */
/* Location: ./application/models/M_komputer.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-03-15 05:31:40 */
/* http://harviacode.com */